Update Year 31 - Checkerboard Organization (size).txt
hingston/7-billion-humans-solutions pull request #270
Opened 2021-10-01 09:47 UTC by bmitchell2407

this change makes the solution actually take 7 commands, meeting the size challenge.

2021-11-28 03:51 UTC, Torvin commented
why make it 7 when it's 6 right now?

2021-11-28 12:53 UTC, novativmedias commented
https://en.m.wikipedia.org/wiki/World_population

It is actually 7.9 since this month 

⁣

Le 27 nov. 2021 22:51, à 22:51, Torvin ***@***.***> a écrit:
>why make it 7 when it's 6 right now?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hingston/7-billion-humans-solutions/pull/270#issuecomment-980835179

2021-12-30 07:40 UTC, hingston requested changes
The current solution is 6 lines long and this solution makes it 7 lines long. The lines that count are the in-game lines not the lines in the text files.

2025-04-27 21:34 UTC, hingston commented
Current solution 6 lines:
![image](https://github.com/user-attachments/assets/babd8af6-b853-4baa-8d9f-5b89b27c81c2)

Your solution 7 lines:
![image](https://github.com/user-attachments/assets/6e667551-311e-48e6-85ac-077e356c9585)

It is a nice solution but doesn't break the record sorry.

2025-04-27 21:34 UTC, closed without merging